/**
 * CREA-911
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@neiba.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Fichier {
    fchId?: number;

    fchUid?: string;

    fchHash?: string;

    fchExtension?: string;

    fchDateAjout?: string;

    fchDateModif?: string;

    fchLink?: string;

    fchEtat?: boolean;

    fkTypeFichierId?: number;

}
